export const recipesTest = [
    {
        RCP_SEQ: 17,
        RCP_NM: "칼륨 듬뿍 고구마죽",
        RCP_WAY2: "끓이기",
        RCP_PAT2: "후식",
        INFO_WGT: 0,
        INFO_ENG: 205,
        INFO_CAR: 35,
        INFO_PRO: 3,
        INFO_FAT: 6,
        INFO_NA: 68,
        HASH_TAG: "",
        ATT_FILE_NO_MAIN: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00017_2.png",
        ATT_FILE_NO_MK: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00017_1.png",
        RCP_PARTS_DTLS: "고구마죽 고구마 100g(2/3개), 설탕 2g(1/3작은술), 찹쌀가루 3g(2/3작은술), 물 200ml(1컵), 잣 8g(8알)"
      },
      {
        RCP_SEQ: 16,
        RCP_NM: "누룽지 두부 계란죽",
        RCP_WAY2: "끓이기",
        RCP_PAT2: "밥",
        INFO_WGT: 0,
        INFO_ENG: 380,
        INFO_CAR: 67,
        INFO_PRO: 12,
        INFO_FAT: 7,
        INFO_NA: 271,
        HASH_TAG: "순두부",
        ATT_FILE_NO_MAIN: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00016_2.png",
        ATT_FILE_NO_MK: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00016_1.png",
        RCP_PARTS_DTLS: "채소준비 애호박 30g(1/6개), 표고버섯 20g(2개), 당근 5g(3×2×1cm) 누룽지 죽 누룽지 70g(1/3컵), 순두부 100g(1/4모), 달걀 50g(1개), 참기름 3g(2/3작은술), 소금 약간, 참깨 약간, 흰 후추 약간"
      },
      {
        RCP_SEQ: 9,
        RCP_NM: "오색지라시 스시",
        RCP_WAY2: "끓이기",
        RCP_PAT2: "밥",
        INFO_WGT: 0,
        INFO_ENG: 700,
        INFO_CAR: 138,
        INFO_PRO: 17,
        INFO_FAT: 9,
        INFO_NA: 75,
        HASH_TAG: "",
        ATT_FILE_NO_MAIN: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00009_2.png",
        ATT_FILE_NO_MK: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00009_1.png",
        RCP_PARTS_DTLS: "초밥 밥 210g(1공기) 배합초 식초 20g(1⅓큰술), 설탕 10g(2작은술), 소금 약간 오색지라시 달걀노른자 40g(달걀2개), 표고버섯 10g(1장), 새송이버섯 20g(3개), 새우 25g(4마리), 홍피망 10g(1/8개), 청피망 10g(1/8개), 양파 5g(5×1cm), 대두유 20g(1⅓큰술), 참기름 10g(2작은술), 식용유 약간"
      },
      {
        RCP_SEQ: 10,
        RCP_NM: "두부 곤약 나물 비빔밥",
        RCP_WAY2: "끓이기",
        RCP_PAT2: "밥",
        INFO_WGT: 0,
        INFO_ENG: 225,
        INFO_CAR: 26,
        INFO_PRO: 14,
        INFO_FAT: 7,
        INFO_NA: 97,
        HASH_TAG: "두부 곤약잡곡밥",
        ATT_FILE_NO_MAIN: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00010_2.png",
        ATT_FILE_NO_MK: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00010_1.png",
        RCP_PARTS_DTLS: "두부 110g(⅓모), 흰쌀 15g, 현미쌀 3g, 찹쌀 3g, 실곤약 3g 나물준비 콩나물 15g(15개), 표고버섯 4g(1/2장), 애호박 10g(5×2×1cm), 고사리 15g(7줄기), 당근 15g(5×3×1cm), 소금 3g(2/3작은술), 소금 약간(나물데침) 비빔고추장 소스 초고추장 5g(1작은술), 플레인요거트 10g(2작은술), 참기름 2g(1/3작은술) 곁들임 새싹채소 3g"
      },
      {
        RCP_SEQ: 11,
        RCP_NM: "저염 간장을 이용한 닭개장 비빔밥",
        RCP_WAY2: "끓이기",
        RCP_PAT2: "밥",
        INFO_ENG: 570,
        INFO_CAR: 71,
        INFO_PRO: 27,
        INFO_FAT: 20,
        INFO_NA: 224,
        INFO_WGT:   0,
        HASH_TAG: "가슴살",
        ATT_FILE_NO_MAIN: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00011_2.png",
        ATT_FILE_NO_MK: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00011_1.png",
        RCP_PARTS_DTLS: "흑미밥 쌀 90g, 검은 쌀 10g 닭가슴살 삶기 닭가슴살 40g(1/3개), 월계수 잎 2장, 후추 약간 나물준비 숙주 20g(1/20봉지), 토란대 20g(5cm, 5개), 고사리 20g(10줄기) 고명 달걀 50g(1개), 대파 10g(5cm), 들기름 5g(1작은술), 실고추약간, 소금약간 들깨 소스 들깨가루 15g(1큰술), 고추기름 10g(2작은술), 꿀 8g(1⅔작은술), 저염간장 8g(1⅔작은술)"
      },
      {
        RCP_SEQ: 12,
        RCP_NM: "취나물 비빔밥 & 청국장 쌈장",
        RCP_WAY2: "끓이기",
        RCP_PAT2: "밥",
        INFO_WGT: "",
        INFO_CAR: 73,
        INFO_PRO: 10,
        INFO_FAT: 9,
        INFO_ENG: 415,
        INFO_NA: 188,
        HASH_TAG: "다짐육",
        ATT_FILE_NO_MAIN: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00012_2.png",
        ATT_FILE_NO_MK: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00012_1.png",
        RCP_PARTS_DTLS: [
          "취나물밥: 밥 210g(1공기)", "다진 쇠고기 20g(1⅓큰술)", "취나물 20g(8줄기)",
          "다진 양파 5g(1작은술)", "다진마늘 5g(1작은술)", "간장 약간", "매실즙 3g(2/3작은술)",
          "참기름 2g(1/3작은술)", "참깨 5g(1작은술)", "소금 약간",
          "청국장쌈장: 청국장 20g(1⅓큰술)", "된장 2g(1/3작은술)", "콩가루 5g(1작은술)",
          "멸치가루 2g(1/3작은술)", "쌀뜨물 30g(2큰술)", "다진 양파 7g(1/2큰술)",
          "다진 호박 7g(1/2큰술)", "다진 당근 7g(1/2큰술)", "다진 표고버섯 7g(1/2큰술)",
          "다진 호두 5g(1작은술)", "참기름 2g(1/3작은술)"
        ]
      },
      {
        RCP_SEQ: 13,
        RCP_NM: "해물 채소장을 넣은 곰취 쌈밥",
        RCP_WAY2: "끓이기",
        RCP_PAT2: "밥",
        INFO_WGT: "",
        INFO_ENG: 250,
        INFO_CAR: 50,
        INFO_PRO: 8,
        INFO_FAT: 2,
        INFO_NA: 371,
        HASH_TAG: "잡곡쌀",
        ATT_FILE_NO_MAIN: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00013_2.png",
        ATT_FILE_NO_MK: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00013_1.png",
        RCP_PARTS_DTLS: [
          "잡곡밥: 잡곡밥 140g(2/3공기)",
          "곰취쌈: 곰취 30g, 소금 약간",
          "해물채소장: 조갯살 10g", "새우살 10g", "오징어살 15g", "감자 18g(1/6개)",
          "애호박 18g(1/9개)", "양파 15g(1/8개)", "청양고추 2g(1/5개)", "표고버섯 5g(1/2장)",
          "대파 2g(1cm)", "마늘 3g(1/2쪽)", "쌈장 10g(2작은술)", "설탕 약간", "참기름 약간",
          "카놀라유 5g(1작은술)", "고춧가루 약간",
          "무초절임: 무 65g(6×5×2cm)", "식초 30g(2큰술)", "설탕 15g(1큰술)", "물 50ml(1/4컵)"
        ]
      },
      {
          RCP_SEQ: 14,
          RCP_NM: "단호박 케일밥",
          RCP_WAY2: "끓이기",
          RCP_PAT2: "밥",
          INFO_WGT: "",
          INFO_ENG: 375,
          INFO_CAR: 78,
          INFO_PRO: 7,
          INFO_FAT: 4,
          INFO_NA: 14,
          HASH_TAG: "단호박",
          ATT_FILE_NO_MAIN: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00014_2.png",
          ATT_FILE_NO_MK: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00014_1.png",
          RCP_PARTS_DTLS: [
            "단호박찰밥: 찹쌀 100g", "밤 30g(3개)", "은행 20g(8알)", "잣 10g(10알)", "단호박 40g(4×8cm)",
            "대추 5g(2개)", "케일 3장(연잎도 가능)",
            "케일소스: 케일이 쪄진 물 100ml(1/2컵)", "설탕 15g(1큰술)"
          ]
        },
        {
          RCP_SEQ: 15,
          RCP_NM: "오색영양밥 롤",
          RCP_WAY2: "끓이기",
          RCP_PAT2: "밥",
          INFO_WGT: "0",
          INFO_ENG: 690,
          INFO_CAR: 103,
          INFO_PRO: 25,
          INFO_FAT: 20,
          INFO_NA: 170,
          HASH_TAG: "",
          ATT_FILE_NO_MAIN: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00015_2.png",
          ATT_FILE_NO_MK: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00015_1.png",
          RCP_PARTS_DTLS: [
            "영양밥: 찹쌀 100g", "흑미30g", "바지락 50g(16개)", "강낭콩 15g(1큰술)", "완두콩 15g(1큰술)", "메주콩 15g(1큰술)", "은행 10g(4알)",
            "오색준비: 달걀 100g(2개)", "애호박 60g(1/3개)", "가지 40g(1/4개)", "당근 40g(1/4개)", "표고버섯 30g(2장)", "대추 10g(5개)", "호두",
            "소스: 다진 호두 10g(2작은술)", "잣가루 2g(1/3작은술)", "참기름 20g(1⅓큰술)",
            "곁들임: 치자가루 5g(1작은술)", "연근 6g(1cm)", "식초 5g(1작은술)", "카놀라유 10g(2작은술)", "새싹채소 6g"
          ]
        },
        {//영양성분 잏상
          RCP_SEQ: 28,
          RCP_NM: "새우 두부 계란찜",
          RCP_WAY2: "찌기",
          RCP_PAT2: "반찬",
          INFO_WGT: "220",
          INFO_ENG: 3,
          INFO_CAR: 14,
          INFO_PRO: 17,
          INFO_FAT: 99,
          INFO_NA: 0,
          HASH_TAG: "연두부",
          ATT_FILE_NO_MAIN: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00028_2.png",
          ATT_FILE_NO_MK: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00028_1.png",
          RCP_PARTS_DTLS: [
            "새우두부계란찜: 연두부 75g(3/4모)", "칵테일새우 20g(5마리)", "달걀 30g(1/2개)", "생크림 13g(1큰술)", "설탕 5g(1작은술)", "무염버터 5g(1작은술)",
            "고명: 시금치 10g(3줄기)"
          ]
        },
        {
          RCP_SEQ: 29,
          RCP_NM: "부추 콩가루 찜",
          RCP_WAY2: "찌기",
          RCP_PAT2: "반찬",
          INFO_WGT: "215",
          INFO_ENG: 20,
          INFO_CAR: 14,
          INFO_PRO: 9,
          INFO_FAT: 240,
          INFO_NA: 0,
          HASH_TAG: "",
          ATT_FILE_NO_MAIN: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00029_2.png",
          ATT_FILE_NO_MK: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00029_1.png",
          RCP_PARTS_DTLS: [
            "부추 콩가루 찜: 조선부추 50g", "날콩가루 7g(1⅓작은술)",
            "양념장: 저염간장 3g(2/3작은술)", "다진 대파 5g(1작은술)", "다진 마늘 2g(1/2쪽)", "고춧가루 2g(1/3작은술)", "요리당 2g(1/3작은술)",
            "참기름 2g(1/3작은술)", "참깨 약간"
          ]
        },
        {
          RCP_SEQ: 30,
          RCP_NM: "연근 구기자 물김치",
          RCP_WAY2: "끓이기",
          RCP_PAT2: "반찬",
          INFO_WGT: "30",
          INFO_ENG: 6,
          INFO_CAR: 2,
          INFO_PRO: 0,
          INFO_FAT: 109,
          INFO_NA: 0,
          HASH_TAG: "",
          ATT_FILE_NO_MAIN: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00030_2.png",
          ATT_FILE_NO_MK: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00030_1.png",
          RCP_PARTS_DTLS: [
            "연근 손질 물 200ml(1컵)", "식초 15g(1큰술)",
            "연근 구기자 물김치: 동치미국물 40g(2⅔큰술)", "연근 30g(4cm)", "무 20g(3×3×1cm)", "사과 30g(1/5개)", "배추 10g(1장)", "구기자 10g(5개)",
            "오이 5g(2cm)", "돌미나리 5g", "쪽파 5g"
          ]
        },
        {
          RCP_SEQ: 31,
          RCP_NM: "방울토마토 소박이",
          RCP_WAY2: "기타",
          RCP_PAT2: "반찬",
          INFO_WGT: "45",
          INFO_ENG: 9,
          INFO_CAR: 2,
          INFO_PRO: 1,
          INFO_FAT: 277,
          INFO_NA: 0,
          HASH_TAG: "방울토마토",
          ATT_FILE_NO_MAIN: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00031_2.png",
          ATT_FILE_NO_MK: "http://www.foodsafetykorea.go.kr/uploadimg/cook/10_00031_1.png",
          RCP_PARTS_DTLS: [
            "방울토마토 소박이: 방울토마토 150g(5개)", "양파 10g(3×1cm)", "부추 10g(5줄기)",
            "양념장: 고춧가루 4g(1작은술)", "멸치액젓 3g(2/3작은술)", "다진 마늘 2.5g(1/2쪽)", "매실액 2g(1/3작은술)",
            "설탕 2g(1/3작은술)", "물 2ml(1/3작은술)", "통깨 약간"
          ]
        }
    ];